Update TRIAGE process to add the triage team
json-schema-org/.github pull request #28
Opened 2024-10-26 10:39 UTC by benjagm

As discussed [here](https://github.com/json-schema-org/TSC/issues/14) I am creating this PR to create the Triage Team.

2024-10-28 18:40 UTC, gregsdennis requested changes

2024-10-31 03:12 UTC, jdesrosiers approved these changes
lgtm. Just found one typo.

2024-10-31 03:12 UTC, jdesrosiers commented on TRIAGE.md
> +The JSON Schema iriage team is a group dedicated towards improving workflow efficiency through thoughtful review and triage of open issues and pull requests. This helps contributors receive timely fe
```suggestion
The JSON Schema triage team is a group dedicated towards improving workflow efficiency through thoughtful review and triage of open issues and pull requests. This helps contributors receive timely feedback and enables core developers to focus on reviewed items which reduces their workload.
```

2024-11-08 06:20 UTC, benjagm commented on TRIAGE.md
> +** Becoming a member of the JSON Schema triage team **
I updated the pr to replace those bold style with headers. Thanks Greg.

2024-11-08 06:29 UTC, gregsdennis approved these changes

2024-11-08 06:56 UTC, merged